#!/usr/bin/env ruby

require File.expand_path("../lib/tracker", __dir__)


Tracker::logger = Logger.new(STDOUT)

if ARGV[0].nil? 
  puts "Please input a block_number."
  puts "Usage: pangolin <BLOCK_NUMBER>"
else
  begin
    start_from = Integer(ARGV[0])

    # init client and nft helper
    pangolin = Pangolin.new("wss://pangolin-rpc.darwinia.network")
    nft_helper = SubstrateEvmNftHelper.new(pangolin)

    latest_block_number = pangolin.get_latest_block_number
    Tracker::logger.info "The lasest block number is #{latest_block_number}"

    while true
      begin
        if start_from <= latest_block_number
          Tracker::logger.info "Scan block #{start_from}"
          erc721_events, erc1155_events = nft_helper.get_evm_nft_events(start_from)
          Tracker::logger.info "#{erc721_events.length} erc721 events scanned"
          Tracker::logger.info "#{erc1155_events.length} erc1155 events scanned"
          start_from += 1
        else
          Tracker::logger.info "Sleep 12 seconds."
          sleep(12)
          latest_block_number = pangolin.get_latest_block_number
          Tracker::logger.info "The lasest block number is #{latest_block_number}"
        end
      rescue => ex
        Tracker::logger.error ex
        Tracker::logger.error ex.backtrace
        sleep(30)
      end
    end

  rescue ArgumentError => ex
    if ex.message.start_with?("invalid value for Integer")
      puts "Please input an integer as the block number."
      puts "Usage: pangolin <BLOCK_NUMBER>"
    end
  end
end

